### PR TITLE
Epic 3: concurrency and resource safety

### LINKED ISSUE #38: Add a bounded state table with count and age limits
## Context

This issue satisfies the following requirements, quoted from [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md):

> FR-concurrency-safety-7 — Every state table holds no more than a maximum entry count.

> FR-concurrency-safety-8 — Every state table evicts an entry that has not been read for longer than a maximum age.

> FR-concurrency-safety-9 — The maximum entry count and the maximum age are constructor arguments.

> FR-concurrency-safety-10 — A state table evicts the least recently used entry when it reaches its maximum entry count.

## What to build

New file `ja4plus/utils/state_table.py`. This is the shared structure every stateful fingerprinter moves onto in the next issue.

Eviction runs on packet arrival, not on a timer. The library starts no thread.

Eviction by age uses the packet timestamp when the packet carries one, and the wall clock otherwise. A capture file replays faster than real time, and a wall clock would evict entries that the capture still needs.

An eviction pass runs at most once per 1000 packets, so eviction cost stays proportional to traffic. Defaults: 10000 entries, 300 seconds. Measure a baseline and state the memory ceiling in the pull request.

## Acceptance criteria

- [ ] A state table holds no more than its maximum entry count.
- [ ] An entry that receives no packet for longer than the maximum age is absent afterwards.
- [ ] The least recently used entry is evicted when the table reaches its maximum count.
- [ ] `max_connections` of zero or a negative number raises `ValueError`.

## Links

- Feature: [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md)
- Design: [`docs/specs/spec.md`](docs/specs/spec.md)
- Writing standard: [`.claude/rules/ste.md`](.claude/rules/ste.md)
- Conformance rules: [`.claude/rules/conformance.md`](.claude/rules/conformance.md)

Part of #14

### LINKED ISSUE #39: Move every fingerprinter onto the bounded state table
## Context

This issue satisfies the following requirements, quoted from [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md):

> FR-concurrency-safety-7 — Every state table holds no more than a maximum entry count.

> FR-concurrency-safety-8 — Every state table evicts an entry that has not been read for longer than a maximum age.

## What to build

The stateful fingerprinters are JA4 (QUIC CRYPTO fragments keyed by connection identifier), JA4H and JA4X (reassembled TCP segments), JA4L (handshake timestamps and TTL values) and JA4SSH (packet lengths, bare-ACK counts and banner strings).

`ja4plus/fingerprinters/ja4.py:299` holds `_quic_fragments` and `_quic_dcid_to_tuple`, which grow without limit when a QUIC handshake never completes. A flood of QUIC Initials with distinct connection identifiers is an unbounded allocation today.

`cleanup_connection` stays. It is the caller's way to evict early, and the port has the same method.

## Acceptance criteria

- [ ] Feeding 1000000 packets across 100000 distinct connections holds resident memory below the stated ceiling.
- [ ] Every state table reports an entry count no greater than `max_connections`.
- [ ] The conformance suite still passes on all 37 vectors.

## Links

- Feature: [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md)
- Design: [`docs/specs/spec.md`](docs/specs/spec.md)
- Writing standard: [`.claude/rules/ste.md`](.claude/rules/ste.md)
- Conformance rules: [`.claude/rules/conformance.md`](.claude/rules/conformance.md)

Part of #14
Depends on #38

### LINKED ISSUE #40: Add the thread_safe argument and per-fingerprinter locks
## Context

This issue satisfies the following requirements, quoted from [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md):

> FR-concurrency-safety-1 — `Processor.__init__` accepts a `thread_safe` argument.

> FR-concurrency-safety-2 — The `thread_safe` argument defaults to `True`.

> FR-concurrency-safety-3 — When `thread_safe` is `True`, two threads may call `process_packet` on one processor at the same time.

> FR-concurrency-safety-4 — When `thread_safe` is `True`, a call to `reset` does not corrupt a state table that another thread is reading.

> FR-concurrency-safety-5 — When `thread_safe` is `False`, the processor acquires no lock.

> FR-concurrency-safety-6 — The processor passes its `thread_safe` value to every fingerprinter it builds.

## What to build

The lock is one lock per fingerprinter, not one global lock. Ten fingerprinters holding ten locks let ten threads work at once on different methods.

The lock is a `threading.RLock`, because a fingerprinter may call its own method that also locks.

`thread_safe=False` is a promise the caller makes, not a mode the library checks. The documentation states that a caller who breaks the promise gets undefined results.

There is no lock anywhere in the package today, and `Processor.get_shard_key` exists so a caller can spread traffic across workers. Concurrency is expected; nothing states what is safe.

## Acceptance criteria

- [ ] Eight threads feeding one `Processor()` for 60 seconds produce the same fingerprint set as one thread feeding the same packets.
- [ ] Eight threads feeding one `Processor()` raise no exception.
- [ ] A test that calls `reset` from one thread while eight threads process packets raises no exception.
- [ ] `Processor(thread_safe=False)` acquires no lock, proven by a test that replaces the lock with an object that fails when acquired.

## Links

- Feature: [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md)
- Design: [`docs/specs/spec.md`](docs/specs/spec.md)
- Writing standard: [`.claude/rules/ste.md`](.claude/rules/ste.md)
- Conformance rules: [`.claude/rules/conformance.md`](.claude/rules/conformance.md)

Part of #14
Depends on #39

### LINKED ISSUE #41: Report processor statistics
## Context

This issue satisfies the following requirements, quoted from [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md):

> FR-concurrency-safety-11 — The processor reports how many entries each state table holds.

> FR-concurrency-safety-12 — The processor reports how many entries it evicted.

## What to build

`ProcessorStats` reports the entry count, the eviction count and the packet count for one method. Epic 4 makes it a typed dataclass; a plain object is acceptable here.

A connection that is evicted and then sends another packet creates a new entry, and the fingerprint for that connection may be incomplete. Record that in the statistics so an operator can see it happening.

The port has no equivalent. This is an addition, not a divergence: parity rule 2 applies only where the port has already shipped a choice.

## Acceptance criteria

- [ ] `Processor().stats()` returns one entry per method.
- [ ] Each entry reports the state-table entry count, the eviction count and the packet count.

## Links

- Feature: [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md)
- Design: [`docs/specs/spec.md`](docs/specs/spec.md)
- Writing standard: [`.claude/rules/ste.md`](.claude/rules/ste.md)
- Conformance rules: [`.claude/rules/conformance.md`](.claude/rules/conformance.md)

Part of #14
Depends on #40

### LINKED ISSUE #42: Make the module-level lookup client thread-safe and bound its cache
## Context

This issue satisfies the following requirements, quoted from [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md):

> FR-concurrency-safety-13 — The module-level `lookup` function builds its client once, and two threads that call it at the same time receive one client.

> FR-concurrency-safety-14 — The lookup cache holds no more than a maximum entry count.

## What to build

`ja4plus/ja4db.py:132` holds `_default_client = None` and builds it lazily at line 138 with no guard, so two threads can build two clients. `JA4DBClient._cache` at line 68 is a plain dictionary that grows without limit and stores a result for every fingerprint ever looked up.

The port solves the same problem with `sync.Once` over a map that is read-only after load. Use the equivalent guard here.

Cache a miss as well as a hit, so a repeated miss costs nothing.

## Acceptance criteria

- [ ] Two threads that call `ja4plus.ja4db.lookup` at the same time receive results from one client instance.
- [ ] The lookup cache holds no more than its maximum entry count.

## Links

- Feature: [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md)
- Design: [`docs/specs/spec.md`](docs/specs/spec.md)
- Writing standard: [`.claude/rules/ste.md`](.claude/rules/ste.md)
- Conformance rules: [`.claude/rules/conformance.md`](.claude/rules/conformance.md)

Part of #14

### LINKED ISSUE #43: Add the thread-safety and memory-bound suites and document the contract
## Context

This issue satisfies the following requirements, quoted from [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md):

> FR-concurrency-safety-15 — The documentation states the concurrency contract.

## What to build

New files `tests/test_thread_safety.py` and `tests/test_memory_bounds.py`.

The contract to state: a processor is safe to share between threads by default; a caller who shards traffic with `get_shard_key` and wants the fastest path constructs `Processor(thread_safe=False)` and must not then share it.

This is the last issue in the epic and proves the whole contract. Epic 8 expands the README text into a documentation page.

## Acceptance criteria

- [ ] `pytest tests/test_thread_safety.py` passes.
- [ ] `pytest tests/test_memory_bounds.py` passes.
- [ ] The README states the concurrency contract in one paragraph.

## Links

- Feature: [`docs/specs/features/03-concurrency-safety.md`](docs/specs/features/03-concurrency-safety.md)
- Design: [`docs/specs/spec.md`](docs/specs/spec.md)
- Writing standard: [`.claude/rules/ste.md`](.claude/rules/ste.md)
- Conformance rules: [`.claude/rules/conformance.md`](.claude/rules/conformance.md)

Part of #14
Depends on #40

### LINKED ISSUE #285: Bound the JA4TS prefixes table that the Epic 3 merge orphans
Found by the project manager at the Epic 3 gate on 2026-08-08, resolving the merge of `dev`
into `epic/14-concurrency-and-resource-safety`.

## The defect the merge would introduce

**#246 added a sixteenth state table that Epic 3 never saw.** The two branches were live at
the same time and neither could read the other.

`ja4plus/fingerprinters/ja4ts.py` on `dev` holds `SynAckTracker.prefixes`, a plain dictionary
keyed by connection that stores part a through part d of the first SYN-ACK, which the RST
value of #246 reads. **On `dev` it is bounded transitively and correctly**: `_expire` and
`_evict` bound `times`, and both call `drop(key)`, which removes the key from `times` **and**
from `prefixes`.

**Epic 3 removes that mechanism.** #39 replaced `self.times = {}` with a `BoundedStateTable`,
and #38's table **evicts internally** — it calls neither `drop` nor any caller hook. So after
the merge:

- `times` stays bounded.
- **`prefixes` grows without limit**, because nothing removes a key that `times` evicted.

**That is the exact rule Epic 3 exists to enforce**, stated in `CLAUDE.md`: a structure that
survives across packets holds a maximum entry count and a maximum age.

## Why no gate caught it

Both branches were green. **#39 and #41 swept for state tables and found thirteen and then
fifteen — neither sweep could see `prefixes`, because it did not exist on their base.**
`tests/foxio_deviations.json` does not move and no fingerprint changes, so no conformance
case fails either.

**Two live integration branches cannot see each other.** Session 9 recorded the same shape
and the batch gate caught it then; the gate caught it again here.

## What to build

- [ ] Merge `origin/dev` into `epic/14-concurrency-and-resource-safety` and resolve every
      conflict in `ja4plus/fingerprinters/ja4ts.py`.
- [ ] **`prefixes` holds a maximum entry count and a maximum age**, in lockstep with `times`,
      so a key evicted from one is absent from the other.
- [ ] **Prove the leak exists before you fix it.** Build the case that fills `times` past its
      bound and reads `len(prefixes)`; show it fails on the merged tree before your repair
      and passes after.
- [ ] `Processor.stats()` reports the table, and the count of state tables rises from 15.
      **Re-measure that count; do not assume it becomes 16.**
- [ ] The `reset` conflict keeps Epic 3's lock and clears both tables.
- [ ] The superseded `_expire` and `_evict` go, or the resolution states why they stay.

## The invariant

`tests/foxio_deviations.json` holds **137 keys** against **137 `xfailed`**, and no fingerprint
moves. The RST value #246 built must still be produced: its capture and its cases stay green.

### PR DESCRIPTION
**Pull request by Crank-Git**
**Epic 3, concurrency and resource safety.** Tracking issue #14. Session 10, 2026-08-08.

**Before this epic, six state tables in this package held no bound at all, and #179 had
recorded that fact since session 7.** The measured number turned out to be sixteen.

## Members

Closes #38
Closes #39
Closes #42
Closes #40
Closes #41
Closes #43
Closes #285

| Member | Round | What it landed |
|---|---|---|
| #38 | 81 | `BoundedStateTable` — count bound, age bound, least-recently-used eviction |
| #39 | 82 | **Thirteen** state tables moved onto it, across six fingerprinters |
| #42 | 83 | One lookup client under a lock, and the lookup cache bounded at 100000 |
| #40 | 84 | `thread_safe`, defaulting to `True`, and one `RLock` for each fingerprinter |
| #41 | 85 | `Processor.stats()` — entries, evictions, packets, returned connections |
| #43 | 86 | The memory-bound suite and the documented concurrency contract |
| #285 | 87 | The sixteenth table, which the merge with `dev` orphaned |

## The count of state tables moved four times, and every move came from a better method

| Reading | Count | Why it changed |
|---|---|---|
| #179, session 7 | 6 | The list written into an issue |
| #39 | 13 | A sweep for every container assigned to `self` that survives a packet |
| #41 | 15 | A **nested** walk — a flat `vars()` walk reports 14 and misses `SynAckTracker.times` |
| #285 | 16 | #246 added one on a branch Epic 3 could not see |

**Only the last of those four was caused by new code.** The other three were the same
package, counted better. `STATE_TABLE_COUNT` is now pinned at 16 and a case compares an
independent walk against `Processor.stats()`, so a change that hides a table from either one
fails.

## The epic gate caught a defect that no continuous-integration run would have

**#246 landed `SynAckTracker.prefixes` in batch 21 while Epic 3 was live.** On `dev` it is
bounded transitively: `_expire` and `_evict` bound `times` and both call `drop(key)`, which
clears both tables. **Epic 3 deletes that mechanism**, because `BoundedStateTable` evicts
internally and calls no hook. The merge would therefore have left `prefixes` growing without
limit — **the exact rule this epic exists to enforce.**

Both branches were green. The register does not move and no fingerprint changes, so no
conformance case fails. **Two live integration branches cannot see each other**, and the
gate is the only place that reads them together. #285 repaired it with an eviction hook, and
proved the leak with a failing case before repairing it.

**#285 also found two semantic conflicts git did not flag** — two `SynAckTracker.record` call
sites reading `TypeError: missing 1 required positional argument`. Git reports a conflict
where two branches edit the same lines; it reports nothing where one branch changes a
signature the other calls.

## Two premises the project manager wrote were disproven by measurement

- **The cache bound.** The brief for #42 said it comes from
  `features/03-concurrency-safety.md`. **That file names no bound for this table** — the
  `## Terms` definition of a state table is per-connection fingerprinter data, which
  `JA4DBClient` is not. It is `features/07-db-enrichment.md:134`, `cache_size: int = 100_000`.
- **The cause of the concurrent difference.** Round 84 and the brief for #43 said "the
  eviction order of the bounded tables". #43 separated the two bounds over the same 2047
  packets: **the age bound alone causes it, 5 of 5 with both bounds and 0 of 5 with the age
  bound raised.** The five captures span **183 days**, so concatenating them jumps the clock.
  **One thread loses a value too**, which removes "race" as the explanation. Round 86 carries
  the correction; the Changelog is append-only, so round 84 stands.

## The contract this epic documents is narrower than "thread safe", on purpose

`README.md` states it in one paragraph. A caller who gives each thread **whole connections**,
which is what `Processor.get_shard_key` exists for, reads the fingerprint set a single thread
reads. A caller who splits one connection across threads on a workload that exceeds a table
bound may not. **That is a consequence of bounding, and a reader must not have to discover
it.** `thread_safe=False` is a promise the caller makes, not a mode the library checks.

**No memory ceiling is stated anywhere.** The measurement forces a floor near 239 MiB and
forces no ceiling; **#279 holds that number for the user.**

## What the removal sweeps found, which is the reason this epic is trustworthy

Every lock and every bound was proven by removal, not by a green suite.

- **#40's first sweep found six locks at 0 failures of 20, and a base-class lock at 0 of 20.**
  They protected nothing. Six gained real mutual-exclusion cases and the base-class lock was
  deleted.
- **#42's first concurrency case reported 0 failures out of 30 runs with and without its
  lock.** Replaced with one that fails 17 of 20 unguarded.
- **#43's first memory suite could not fail on the age bound**, 0 of 3 on removal. Repaired.
- **#39's self-review found three age passes running on every packet with no reason**, one of
  them scanning up to 1000 entries per payload-carrying TCP packet.

A plain `Lock` in place of the `RLock` deadlocks 3 runs of 3. The measured cost is **1.22%
for the locks** and **1.8% for the statistics counters**.

## The invariant

**137 register keys against 137 `xfailed`, unchanged through all seven members.** No
fingerprint moved: the 38-capture replay produces the same values byte-for-byte, and
`tests/foxio_deviations.json` is byte-identical to `dev`.

```
pytest tests/ -m spec_validation       1477 passed, 143 skipped, 137 xfailed
pytest tests/ -m "not spec_validation"  1641 passed, 8 xfailed, 93 subtests passed
```

## Continuous integration

Every member merged as a draft pull request carrying `[skip ci]`. **This pull request is the
epic's one continuous-integration run.**

### CODE REVIEW

**Comment by Crank-Git** [comment]
**Note from the project manager, 2026-08-08. This pull request first opened with no
continuous-integration run, and the cause was a project manager error.**

**#286 was merged with `--squash`, and it carried the merge of `dev` into this branch.** A
squash collapses a merge commit into a single ordinary commit, so **the parentage is lost**:
`git merge-base --is-ancestor origin/dev <epic head>` reported false, git saw `dev`'s changes
with no shared history, and the pull request went `CONFLICTING`. **GitHub cannot compute a
merge reference for a conflicting pull request, so no `pull_request` workflow started** — the
check count was zero rather than red, which is why it did not look like a failure.

**The repair records the parentage rather than changing any content.** `origin/dev` is merged
again; both conflicting files resolve to this branch's version, because #285 had already
produced and verified that merged content. Verified after the repair:

- `origin/dev` is an ancestor of this branch.
- `tests/foxio_deviations.json` is byte-identical to `dev`.
- Changelog rounds **76 to 80** from batch 21 are present, and the file reads 76 to 87 in
  numeric order.
- The RST code of #246 is present.
- `1477 passed, 143 skipped, 137 xfailed` and `1641 passed, 8 xfailed`; `ruff check` and
  `ruff format --check` clean.

**The rule that follows: a pull request that carries a merge of the integration target is
merged with `--merge`, never with `--squash`.** Every other sub-merge in this session was a
single-purpose branch and squashing those remains correct.

**A check count of zero is not a pass.** It was read as one for several minutes here.
